(() => {
  'use strict';
  const key='zyklus-bracks-e1-v1';
  const host=document.createElement('section');
  host.id='bracksChapter';host.hidden=true;host.setAttribute('role','dialog');host.setAttribute('aria-modal','true');host.setAttribute('aria-labelledby','bracksTitle');
  document.querySelector('main').append(host);
  const evidence=[
    {id:'register',label:'The register',title:'One line. One dash.',text:'Thursday transport from Level Ten. Accepted at 11:40. Cloth: nine bundles. Containers: forty-one. Kitchen: two wagons. Return: —',speaker:'Falk',quote:'You can copy it. The book stays. The book is the reason we don’t have trouble here.',note:'Copy the line. The original stays on the lectern.'},
    {id:'slips',label:'Daily slips',title:'Paper nobody threw away.',text:'Rows of daily slips hang in clips. The register records the arrivals. Falk confirms that no arrival from a house has come in during the last three weeks.',speaker:'Falk',quote:'Nobody comes from a house in the stream. Houses do it themselves. Their own date, their own wagon, two people with it, and a signature I don’t know. Nine times in eleven years.',note:'An empty stream and a separate house arrival are different things. Check both.'},
    {id:'box',label:'The found box',title:'Under the lectern.',text:'A tool without a handle. Two spoons. Folded cloth. A medal from the Games. Bracks puts the medal back without examining it. Beneath them lies an access tag.',speaker:'Bracks',quote:'What about things that don’t fit in a stream?',note:'The slip beside the access tag reads: Container, arrival Ten, Thursday. Found under cloth.'},
    {id:'panel',label:'Read the access tag',title:'A name. Still active.',text:'The panel warms. The reading takes longer than usual. Sarn, Lian. Level Ten. Allocation active.',speaker:'Falk',quote:'If you take it, I have to write it down. Your number, your purpose, and the word tag. And the slip goes up in the evening. Everything that concerns a tag goes up. That’s not my rule.',note:'Bracks returns the access tag to the found box. Reading it does not prove who travelled with it.'}
  ];
  // Spoken lines retain the script's straight apostrophes.
  evidence.forEach(item=>item.quote=item.quote.replaceAll('’',"'"));
  const claims=[
    {text:'No arrival in the Return stream from Level Ten on Thursday.',answer:'record',reason:'The dash is in the register. Copy the observation, not an explanation.'},
    {text:'The access tag still has an active Allocation.',answer:'record',reason:'The panel displayed the name and the Allocation. That is an observation.'},
    {text:'Lian travelled with the Thursday transport.',answer:'private',reason:'The access tag travelled. Bracks has not established that its owner travelled with it.'}
  ];
  const deductions=[
    {question:'Which two sources cover both ways a body could arrive?',pair:['register','slips'],answers:['No body arrived by either recorded route in the periods checked.','No transport arrived on Thursday.','The records prove that Toren is alive.'],correct:0,reason:'The register covers the stream. Falk covers separate house arrivals. Neither records a body. That does not prove what happened to Toren.'},
    {question:'Which two sources connect a named person’s access tag to Thursday?',pair:['box','panel'],answers:['Lian was seen in the transport.','Lian’s access tag came with the Thursday transport.','Lian’s Allocation has ended.'],correct:1,reason:'The slip gives the journey. The panel gives the name. Neither places the owner beside the access tag.'}
  ];
  let linked=0,picks=new Set();
  let seen=new Set(),step=0,complete=false,view='hall',selected=null,previous,onDone,notified=false;
  const $=selector=>host.querySelector(selector);
  function load(){seen=new Set();step=0;complete=false;try{const save=JSON.parse(localStorage.getItem(key)||'null');if(save){seen=new Set((Array.isArray(save.seen)?save.seen:[]).filter(id=>evidence.some(e=>e.id===id)));step=Number.isInteger(save.step)?Math.max(0,Math.min(3,save.step)):0;complete=save.complete===true&&seen.size===4&&step===3}}catch{}if(seen.size<4)step=0}
  function save(){try{localStorage.setItem(key,JSON.stringify({seen:[...seen],step,complete}));localStorage.setItem(key+'-links',String(linked))}catch{}}
  function renderLinks(){view='notes';picks=new Set();const d=deductions[linked];shell(`<div class="bracks-paper bracks-linkboard"><small>CONNECT THE EVIDENCE · ${linked+1} / 2</small><h3>${d.question}</h3><p>Select two sources. Then choose what they establish together.</p><div class="bracks-source-grid">${evidence.map(e=>`<button type="button" data-source="${e.id}" aria-pressed="false"><b>${e.label}</b><span>${e.text}</span><span>${e.note}</span></button>`).join('')}</div><div class="bracks-choices">${d.answers.map((a,i)=>`<button type="button" data-conclusion="${i}" disabled>${a}</button>`).join('')}</div><p id="bracksFeedback" role="status"></p><button id="bracksBack" type="button">Examine the evidence again</button></div>`);$('#bracksBack').onclick=()=>{renderHall();focusTitle()};host.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{const id=b.dataset.source;if(picks.has(id))picks.delete(id);else if(picks.size<2)picks.add(id);host.querySelectorAll('[data-source]').forEach(x=>x.setAttribute('aria-pressed',String(picks.has(x.dataset.source))));host.querySelectorAll('[data-conclusion]').forEach(x=>x.disabled=picks.size!==2);$('#bracksFeedback').textContent=picks.size===2?'Two sources selected. What follows?':'Select two sources.'});host.querySelectorAll('[data-conclusion]').forEach(b=>b.onclick=()=>{const f=$('#bracksFeedback');if(!d.pair.every(id=>picks.has(id))){f.textContent='Those sources leave a gap. Check what each one actually records.';return}if(Number(b.dataset.conclusion)!==d.correct){f.textContent='That conclusion goes beyond the evidence, or contradicts it. Read the two sources again.';return}host.querySelectorAll('[data-source],[data-conclusion]').forEach(x=>x.disabled=true);f.textContent=d.reason;const next=document.createElement('button');next.type='button';next.textContent=linked===0?'Next connection →':'Separate fact from inference →';next.onclick=()=>{linked++;save();renderNotes();focusTitle()};f.append(next);next.focus()})}
  function focusTitle(){$('#bracksTitle').focus()}
  function close(){if(host.hidden)return;host.hidden=true;window.dispatchEvent(new Event('bracks-close'));if(previous?.isConnected)previous.focus();onDone=null}
  function shell(body){host.innerHTML=`<div class="bracks-inner"><div class="bracks-head"><div><small>BRACKS · EPISODE ONE</small><h2 id="bracksTitle" tabindex="-1">${view==='hall'?'The missing arrival.':view==='notes'?'The second sheet.':'One sentence stays private.'}</h2></div><button type="button" id="bracksExit">Return to Lian ×</button></div>${body}</div>`;$('#bracksExit').onclick=close}
  function renderHall(){view='hall';const item=evidence.find(e=>e.id===selected);shell(`<p class="bracks-intro">Level Four. Examine the records and the found box. Keep what the evidence says separate from what it suggests.</p><div class="bracks-layout"><div class="bracks-scene" role="group" aria-label="Return hall evidence"><div class="bracks-location">LEVEL FOUR <span>RETURN</span></div>${evidence.map((e,i)=>`<button type="button" class="bracks-point point-${e.id}${seen.has(e.id)?' examined':''}" data-evidence="${e.id}" aria-label="${e.label}${seen.has(e.id)?', examined':''}" ${e.id==='panel'&&!seen.has('box')?'disabled':''}><b>${String(i+1).padStart(2,'0')}</b><span>${e.label}</span>${seen.has(e.id)?'<i aria-hidden="true">✓</i>':''}</button>`).join('')}</div><article class="bracks-paper" aria-live="polite"><small>OBSERVATIONS · ${seen.size} / 4</small>${item?`<h3>${item.title}</h3><p>${item.text}</p><div class="bracks-quote"><small>${item.speaker}</small><blockquote>${item.quote}</blockquote></div><p class="bracks-note">${item.note}</p>`:'<h3>Start with the records.</h3><p>A death is written in the case file. No place of discovery. The arrivals may tell a different story.</p><p class="bracks-note">Select the numbered details. The access tag can be read after examining the found box.</p>'}<button type="button" id="bracksNotes" ${seen.size<4?'disabled':''}>${complete?'Read the second sheet':'Compare the observations'} →</button></article></div><p class="bracks-controls">Select a detail · Tab to move between controls · Escape to return</p>`);host.querySelectorAll('[data-evidence]').forEach(button=>button.onclick=()=>{selected=button.dataset.evidence;seen.add(selected);save();renderHall();$(`[data-evidence="${selected}"]`).focus()});$('#bracksNotes').onclick=()=>{if(complete&&linked===2)renderEnd();else renderNotes();focusTitle()}}
  function renderNotes(){if(linked<2){renderLinks();return}view='notes';if(step>=claims.length){renderEnd();return}const claim=claims[step];shell(`<div class="bracks-desk"><div class="bracks-paper bracks-question"><small>OBSERVATION ${step+1} / ${claims.length}</small><h3>What can the record establish?</h3><p class="bracks-claim">${claim.text}</p><p>Choose where this sentence belongs in your notes. Nothing is filed or sent.</p><div class="bracks-choices"><button type="button" data-kind="record">Recorded observation</button><button type="button" data-kind="private">Private inference</button></div><p id="bracksFeedback" role="status"></p><button type="button" id="bracksBack">Examine the evidence again</button></div><aside class="bracks-reminders"><small>YOUR COPIES</small><p>Thursday · Level Ten<br>Return: —</p><p>House arrival<br>None in the last three weeks.</p><p>Access tag<br>Sarn, Lian. Allocation active.</p><p class="bracks-note">The access tag remains in the found box.</p></aside></div>`);$('#bracksBack').onclick=()=>{renderHall();focusTitle()};host.querySelectorAll('[data-kind]').forEach(button=>button.onclick=()=>{const feedback=$('#bracksFeedback');if(button.dataset.kind!==claim.answer){feedback.textContent=claim.answer==='record'?'This was read directly in the record or on the panel. Check your copies.':'The access tag was found. Its owner was not. That step is an inference.';return}host.querySelectorAll('[data-kind]').forEach(b=>b.disabled=true);feedback.textContent=claim.reason;const next=document.createElement('button');next.type='button';next.textContent=step===2?'Keep the second sheet →':'Next observation →';next.onclick=()=>{step++;save();renderNotes();focusTitle()};feedback.append(next);next.focus()})}
  function renderEnd(){view='end';shell(`<div class="bracks-ending"><small>LEVEL TWO · EVENING</small><p>The copied observations stay on the sheet. Under them, Bracks writes a sentence he cannot put in the case file.</p><div class="bracks-quote"><small>Bracks</small><blockquote>She rode along on Thursday.</blockquote></div><p>The access tag stays on Level Four. The question stays with him.</p><button type="button" id="bracksFinish">${complete?'Return to Lian':'Keep the second sheet'} →</button><button type="button" id="bracksReview">Review the evidence</button></div>`);$('#bracksReview').onclick=()=>{renderHall();focusTitle()};$('#bracksFinish').onclick=()=>{complete=true;save();if(!notified){notified=true;onDone?.()}close()}}
  window.zyklusBracks={open(callback){if(!host.hidden)return;previous=document.activeElement;onDone=callback;notified=false;selected=null;load();try{const n=Number(localStorage.getItem(key+'-links'));linked=Number.isInteger(n)?Math.max(0,Math.min(2,n)):0}catch{linked=0}if(seen.size<4)linked=0;host.hidden=false;renderHall();focusTitle()},close};
  document.addEventListener('keydown',event=>{if(host.hidden)return;event.stopImmediatePropagation();if(event.key==='Escape'){event.preventDefault();close();return}if(event.key==='Tab'){const controls=[...host.querySelectorAll('button:not(:disabled)')],first=controls[0],last=controls.at(-1);if(event.shiftKey&&(document.activeElement===first||!controls.includes(document.activeElement))){event.preventDefault();last?.focus()}else if(!event.shiftKey&&(document.activeElement===last||!controls.includes(document.activeElement))){event.preventDefault();first?.focus()}}},true);
  document.addEventListener('keyup',event=>{if(!host.hidden)event.stopImmediatePropagation()},true);
})();
