(() => {
  'use strict';
  const key='council-e1-v1';
  const moments=[
    {title:'A report reaches the table.',lines:[{speaker:'Talek',quote:'Any other business.'},{speaker:'Kelb',quote:'A Vesk is missing.'},{speaker:'Talek',quote:'Which one.'},{speaker:'Kelb',quote:"The younger one. Toren. Twenty-six. Since Monday. Reported Wednesday evening. There's blood in his room. Enough. No body."}],detail:'The room grows quiet. Rena listens. What is reported here is not the whole story.',claim:'Kelb reports Toren missing. No body.',answer:'record',note:'Keep the attribution: this is Kelb’s report to the Council.',wrong:'No signal stops Rena here. The report can be recorded as a report.'},
    {title:'Three centimetres.',lines:[{speaker:'Talek',quote:'Is anything requested?'},{speaker:'Kelb',quote:'From below, nothing. From Ten, a request for restraint. Verbal.'},{speaker:'Talek',quote:'From whom?'},{speaker:'Kelb',quote:'Halen. For the House.'}],detail:'Talek raises his hand. Three centimetres above the table. Rena stops writing.',claim:'Halen made the request for restraint.',answer:'remember',note:'Rena does not write the name. She remembers it. The omission is the point.',wrong:'Talek’s raised hand means: do not write that. Rena keeps the name in her memory.'},
    {title:'A name without a list.',lines:[{speaker:'Talek',quote:'Who investigates?'},{speaker:'Kelb',quote:'From above. Two would be usual.'},{speaker:'Talek',quote:'Two is usual. And whom?'},{speaker:'Sivar',quote:'Bracks. Investigator on Level Two. Twenty-one years.'},{speaker:'Talek',quote:'Is he good?'},{speaker:'Sivar',quote:'He is thorough.'},{speaker:'Talek',quote:'Is that the same?'},{speaker:'Sivar',quote:'No.'}],detail:'Sivar names him without paper, without searching a list. Nobody asks how he knows.',claim:'Sivar names Bracks as the investigator.',answer:'record',note:'Record what Sivar says. His reason is not established here.',wrong:'Sivar says the name aloud. No signal tells Rena to leave it out.'}
  ];
  const host=document.createElement('section');host.id='councilChapter';host.hidden=true;host.setAttribute('role','dialog');host.setAttribute('aria-modal','true');host.setAttribute('aria-labelledby','councilTitle');document.querySelector('main').append(host);
  let step=0,complete=false,previous,onDone,notified=false;
  const $=s=>host.querySelector(s);
  function save(){try{localStorage.setItem(key,JSON.stringify({step,complete}))}catch{}}
  function load(){step=0;complete=false;try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s){step=Number.isInteger(s.step)?Math.max(0,Math.min(3,s.step)):0;complete=s.complete===true&&step===3}}catch{}}
  function close(){if(host.hidden)return;host.hidden=true;window.dispatchEvent(new Event('council-close'));if(previous?.isConnected)previous.focus();onDone=null}
  function focusTitle(){$('#councilTitle').focus();host.scrollTop=0}
  function shell(body){host.innerHTML=`<div class="council-inner"><div class="council-head"><div><small>RENA · EPISODE ONE</small><h2 id="councilTitle" tabindex="-1">What the record leaves out.</h2></div><button type="button" id="councilExit">Return to Lian ×</button></div><div class="council-art" role="img" aria-label="The Council meets around a long table on Level Nine"><span>LEVEL NINE<br><b>the Council</b></span><div class="council-progress" aria-label="${Math.min(step+1,3)} of 3 moments">${moments.map((m,i)=>`<i class="${i<step?'done':i===step?'current':''}" aria-hidden="true"></i>`).join('')}</div></div>${body}<p class="council-controls">Tab to move between controls · Enter to choose · Escape to return</p></div>`;$('#councilExit').onclick=close}
  function render(){if(step===3){end();return}const m=moments[step];shell(`<div class="council-layout"><article class="council-dialogue"><small>MOMENT ${step+1} / 3</small><h3>${m.title}</h3>${m.lines.map(l=>`<div class="council-line"><small>${l.speaker}</small><blockquote>${l.quote}</blockquote></div>`).join('')}<p class="council-detail">${m.detail}</p></article><aside class="council-paper"><small>AT RENA’S DESK</small><h3>Written. Or remembered.</h3><p>Follow the scene. Keep this observation where Rena keeps it.</p><p class="council-claim">${m.claim}</p><div class="council-choices"><button type="button" data-council-choice="record">In the record</button><button type="button" data-council-choice="remember">In her memory</button></div><p id="councilFeedback" role="status"></p><p class="council-note">This follows the episode. Your choice does not change Rena’s actions.</p></aside></div>`);host.querySelectorAll('[data-council-choice]').forEach(button=>button.onclick=()=>{if(button.dataset.councilChoice!==m.answer){$('#councilFeedback').textContent=m.wrong;return}host.querySelectorAll('[data-council-choice]').forEach(b=>b.disabled=true);$('#councilFeedback').textContent=m.note;const next=document.createElement('button');next.type='button';next.textContent=step===2?'Close the record →':'Next moment →';next.onclick=()=>{step++;save();render();focusTitle()};$('#councilFeedback').append(next);next.focus()})}
  function end(){shell(`<article class="council-ending"><small>THREE MOMENTS · ONE OMISSION</small><h3>The name stays with her.</h3><div class="council-summary"><div><small>IN THE RECORD</small><p>Kelb reports Toren missing.</p><p>Sivar names Bracks.</p></div><div><small>IN HER MEMORY</small><p>Halen. The request for restraint.</p></div></div><p>Rena remembers what she is not allowed to write. Nobody knows that part of her job exists.</p><button type="button" id="councilFinish">${complete?'Return to Lian':'Keep the observation'} →</button><button type="button" id="councilReplay">Read the scene again</button></article>`);$('#councilReplay').onclick=()=>{step=0;complete=false;save();render();focusTitle()};$('#councilFinish').onclick=()=>{complete=true;save();if(!notified){notified=true;onDone?.()}close()}}
  window.zyklusCouncil={quotes:moments.flatMap(m=>m.lines),open(callback){if(!host.hidden)return;previous=document.activeElement;onDone=callback;notified=false;load();host.hidden=false;render();focusTitle()},close};
  document.addEventListener('keydown',event=>{if(host.hidden)return;event.stopImmediatePropagation();if(event.key==='Escape'){event.preventDefault();close();return}if(event.key==='Tab'){const buttons=[...host.querySelectorAll('button:not(:disabled)')],first=buttons[0],last=buttons.at(-1);if(event.shiftKey&&(document.activeElement===first||!buttons.includes(document.activeElement))){event.preventDefault();last?.focus()}else if(!event.shiftKey&&(document.activeElement===last||!buttons.includes(document.activeElement))){event.preventDefault();first?.focus()}}},true);
  document.addEventListener('keyup',event=>{if(!host.hidden)event.stopImmediatePropagation()},true);
})();
