const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');
const episode=window.EPISODE1,images={};let ready=0;
const assets={main:'ebene10-clean-v2.png',university:'university.png',delivery:'delivery.png',outerRing:'outer-ring.png',sarnRoom:'sarn-room.png',levelNine:'level-nine.png',actor:'lian-sprites.png',belaReaction:'bela-rematch.png',toren:'toren-sprites.png',belaWorld:'bela-world-v2.png',malinWorld:'malin-world-v2.png',ravnWorld:'ravn-world-v2.png',worker:'worker.png',cargo:'cargo.png',actorWalk:'lian-walk-v2.png',actorActions:'lian-actions-v2.png',torenWalk:'toren-walk-v2.png',workerWalk:'worker-walk-v2.png'};
for(const [id,src] of Object.entries(assets)){const im=images[id]=new Image();im.onload=()=>{if(++ready===Object.keys(assets).length){$('#start').disabled=false;$('#start').textContent=Object.keys(progress).length?'Continue →':'Enter the city →'}};im.onerror=()=>$('#start').textContent='A scene could not be loaded. Please reload.';im.src=src}
const SAVE='zyklus-episode1-v2';
let progress={};try{const saved=localStorage.getItem(SAVE);if(saved){progress=JSON.parse(saved)}else{const old=JSON.parse(localStorage.getItem('zyklus-episode1-v1')||'{}');for(const k of ['home','university','bela','swim'])if(old[k]===true)progress[k]=true}}catch{}if(!progress||typeof progress!=='object'||Array.isArray(progress))progress={};
let scene='main',x=400,dir=1,active=false,mapOpen=false,journalOpen=false,activity=false,time=0,last=0,jump=0,vy=0,zoom=1.6,targetZoom=1.6,cameraX=650,cameraY=470,W=innerWidth,H=innerHeight,walk=0,red=0,transition=0;
const motion=window.zyklusMotion,body=motion.create(x),follower=motion.create(x-62);let gaitPhase=0,companionSpeed=0,landing=0,takeoff=0,travel=null,traversalHint='';
const keys=new Set(),dialog=$('#dialog');let audio=null,sound=false,ambient=null,ambGain=null,dialogAfter=null,dialogLines=[],line=0,dialogAction=null;
const journalKeys=['home','university','torenMorning','bela','outerRing','door','interrogation','torenNight','delivery','arrivalNine','shiftList','workShift','episodeEnd'];
function resize(){W=innerWidth;H=innerHeight;canvas.width=W;canvas.height=H}addEventListener('resize',resize);resize();
function mark(id){if(progress[id])return;const hadSketch=window.zyklusEggs.allDetails(progress);progress[id]=true;try{localStorage.setItem(SAVE,JSON.stringify(progress))}catch{}updateQuest();toast(!hadSketch&&window.zyklusEggs.allDetails(progress)?'Six details found. A drawing waits in your notebook.':'Added to your notebook.');tone(440,.18)}
function updateQuest(){const tasks={home:'Examine the wooden table in House Sarn.',university:'Visit the university and check the readings.',torenMorning:'Toren is waiting outside the lecture room.',bela:'Meet Bela at the pool.',outerRing:'Leave the pool and take the outer ring.',door:'Return to the panel by the front door.',interrogation:'Malin takes you back inside. Check what was said.',torenNight:'Someone is knocking at the back door. Go and see.',delivery:'Follow Toren through the delivery corridor. Reach the wagon.',arrivalNine:'Look round the transfer hall on Level Nine.',shiftList:'Check the shift list at the third gate.',workShift:'Begin your first shift behind the third gate.',episodeEnd:'Examine the room behind the fourth gate.'};const next=journalKeys.find(k=>!progress[k]);$('#objectiveText').textContent=next?tasks[next]:'Your notebook records Lian’s route through Episode One. More paths open as the series continues.';$('#count').textContent=`${journalKeys.filter(k=>progress[k]).length} / ${journalKeys.length} observations${progress.swim?' · Swam at the pool':''}${Object.keys(progress).some(k=>k.startsWith('detail_'))?' · '+Object.keys(progress).filter(k=>k.startsWith('detail_')&&progress[k]).length+' / 6 details':''}${progress.bracksEnd?' · Bracks: complete':''}`}
if(progress.episodeEnd&&!progress.workShift){delete progress.episodeEnd;try{localStorage.setItem(SAVE,JSON.stringify(progress))}catch{}}
updateQuest();
function restartChapter(){journalOpen=false;$('#notebook').hidden=true;showTalk([{speaker:'Notes',title:'Start again',text:'This clears your observations from the chapter. Your best swimming time and race wins stay.'}],null,{label:'Start again',run:()=>{progress={};try{localStorage.removeItem('zyklus-bracks-e1-v1');localStorage.removeItem('council-e1-v1');localStorage.setItem(SAVE,'{}')}catch{}updateQuest();active=true;$('#intro').hidden=true;go('main',400);toast('A new day on Level Ten.')}})}
const restartButton=document.createElement('button');restartButton.id='restartChapter';restartButton.textContent='Start again';restartButton.onclick=restartChapter;$('#intro').append(restartButton);restartButton.hidden=!Object.keys(progress).length;
const restartNotes=document.createElement('button');restartNotes.textContent='Start again';restartNotes.onclick=restartChapter;$('#notebook').append(restartNotes);
function tone(freq,dur=.2,type='sine',vol=.025){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
$('#sound').onclick=()=>{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();sound=!sound;$('#sound').textContent=sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(sound));tone(330,.2)};

function toast(s){$('#toast').textContent=s;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').textContent='',4000)}
function allowed(dest){return dest==='main'||dest==='university'&&progress.home||dest==='outerRing'&&progress.bela&&progress.torenMorning||dest==='sarnRoom'&&progress.door||dest==='delivery'&&progress.torenNight||dest==='levelNine'&&progress.delivery}
function go(dest,pos){if(!allowed(dest)){toast('Follow your current objective first.');return}if(travel)return;keys.clear();motion.stop(body);travel={dest,pos,elapsed:0,target:mapOpen||activity?x:(nearest()?.x??x),phase:'approach'};canvas.focus()}
function arrive(dest,pos){traversalHint='';scene=dest;x=pos??(dest==='main'?650:230);jump=0;vy=0;motion.stop(body);body.x=x;body.distance=0;body.gaitDistance=0;gaitPhase=0;landing=0;takeoff=0;follower.x=x-62;follower.v=0;keys.clear();transition=1;cameraX=x;cameraY=dest==='main'?470:490;mapOpen=false;$('#mapView').hidden=true;canvas.focus()}
function canMove(){return active&&!travel&&!activity&&!mapOpen&&!journalOpen&&!dialog.open}
function mapToggle(){if(!active||travel||activity||dialog.open||journalOpen)return;mapOpen=!mapOpen;$('#mapView').hidden=!mapOpen;keys.clear();if(mapOpen)renderRoutes();else canvas.focus()}
function renderRoutes(){const routes=[['main',220,'House Sarn','Where your day began.','ebene10-clean-v2.png']];if(progress.home)routes.push(['university',840,'The university','Readings. Questions.','university.png']);if(progress.torenMorning)routes.push(['main',1390,'The pool','Bela is waiting by the pool.','pool-race.png']);if(progress.bela&&progress.torenMorning)routes.push(['outerRing',240,'The outer ring','The way home.','outer-ring.png']);if(progress.door)routes.push(['sarnRoom',800,'Back inside','What was said. What you saw.','sarn-room.png']);if(progress.torenNight)routes.push(['delivery',1330,'The delivery corridor','Behind the homes.','delivery.png']);if(progress.delivery)routes.push(['levelNine',240,'Level Nine','The transfer hall.','level-nine.png']);$('#routes').replaceChildren();for(const [id,pos,title,sub,src]of routes){const b=document.createElement('button');const im=document.createElement('img');im.src=src;im.alt='';const titleEl=document.createElement('strong');titleEl.textContent=title;const small=document.createElement('span');small.textContent=sub;b.append(im,titleEl,small);b.onclick=()=>go(id,pos);$('#routes').append(b)}if(progress.episodeEnd){const c=document.createElement('button');c.innerHTML='<img src="council-room.png" alt=""><strong>the Council</strong><span>Rena · What the record leaves out</span>';c.onclick=councilChapter;$('#routes').append(c);const b=document.createElement('button');b.innerHTML='<img src="bracks-returns.png" alt=""><strong>Bracks</strong><span>A second perspective · Episode One</span>';b.onclick=bracksChapter;$('#routes').append(b)}}
$('#map').onclick=mapToggle;$('#back').onclick=mapToggle;
function notebook(){if(!active||travel||activity||dialog.open||mapOpen)return;journalOpen=!journalOpen;$('#notebook').hidden=!journalOpen;keys.clear();if(journalOpen){$('#notes').replaceChildren();for(const id of journalKeys.filter(k=>progress[k])){const entry=episode.journal[id];if(!entry)continue;const a=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=entry.title;p.textContent=entry.text;a.append(h,p);$('#notes').append(a)}if(!$('#notes').children.length)$('#notes').textContent='Still a blank page. Look round House Sarn.';if(progress.swim){const a=document.createElement('article');a.textContent='The pool · Swam a race against Bela.';$('#notes').append(a)}for(const [id,entry]of Object.entries(window.zyklusDiscoveries?.journal||{})){if(!progress['detail_'+id])continue;const a=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=entry.title;p.textContent=entry.text;a.append(h,p);$('#notes').append(a)}window.zyklusEggs.appendReward($('#notes'),progress);if(window.zyklusEggs.unlocked){const a=document.createElement('article');a.textContent='Bela · Three wins. She wants a rematch.';$('#notes').append(a)}if(progress.episodeEnd){const b=document.createElement('button');b.textContent='Episode One · Look back';b.onclick=()=>{journalOpen=false;$('#notebook').hidden=true;recap()};$('#notes').append(b)}}else canvas.focus()}
$('#journal').onclick=notebook;$('#journalClose').onclick=notebook;
$('#start').onclick=()=>{active=true;$('#intro').hidden=true;if(progress.delivery)go('levelNine',progress.shiftList?1360:240);else if(progress.torenNight)go('delivery',230);else if(progress.door)go('sarnRoom',230);else if(progress.bela&&progress.torenMorning)go('outerRing',230);else if(progress.university&&!progress.torenMorning)go('university',1200);canvas.focus();toast(Object.keys(progress).length?'Your notebook shows what comes next.':'Begin at the wooden table. Press E to examine it.')};
$('#full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Full screen is unavailable here.')}};
$('#minus').onclick=()=>targetZoom=Math.max(.85,targetZoom-.25);$('#plus').onclick=()=>targetZoom=Math.min(2.6,targetZoom+.25);canvas.addEventListener('wheel',e=>{e.preventDefault();targetZoom=Math.max(.85,Math.min(2.6,targetZoom-e.deltaY*.002))},{passive:false});
function showTalk(lines,after=null,action=null){keys.clear();dialogLines=lines;line=0;dialogAfter=after;dialogAction=action;renderTalk();dialog.showModal()}
function renderTalk(){const entry=dialogLines[line];$('#tag').textContent=`${entry.speaker} · ${line+1} / ${dialogLines.length}`;$('#title').textContent=entry.title;$('#text').textContent=entry.text;const face=entry.speaker.toLowerCase(),known=['lian','bela','malin','ravn','toren','meret','halen'].includes(face);$('#portrait').hidden=!known;if(known){$('#portrait').src=`portraits/${face}${['malin','ravn','toren','meret','halen'].includes(face)?'-pixel-v2':''}.png?v=20261009-pixel`;$('#portrait').alt=entry.speaker}$('#close').textContent=line<dialogLines.length-1?'Next ↵':dialogAction?'Back to the city':'Continue ↵';$('#extra').hidden=line<dialogLines.length-1||!dialogAction;if(dialogAction)$('#extra').textContent=dialogAction.label}
function endTalk(useAction=false){const after=dialogAfter,action=dialogAction;dialogAfter=null;dialogAction=null;dialog.close();after?.();if(useAction)action?.run();else canvas.focus()}
$('#close').onclick=()=>{if(line<dialogLines.length-1){line++;renderTalk()}else endTalk()};$('#extra').onclick=()=>endTalk(true);dialog.addEventListener('cancel',()=>{dialogAfter=null;dialogAction=null;keys.clear();requestAnimationFrame(()=>canvas.focus())});
function say(key,after,action){showTalk(episode.dialogues[key],after,action)}
function startActivity(type){activity=true;keys.clear();window.zyklusActivities.open(type,()=>{if(type==='measure'){mark('university')}else mark('delivery')})}
addEventListener('activity-close',()=>{activity=false;keys.clear();if(progress.delivery&&!progress.arrivalNine){go('levelNine',230);say('arrivalNine',()=>mark('arrivalNine'))}else canvas.focus()});
let storyType=null;
function storyActivity(type){activity=true;storyType=type;keys.clear();(type==='workShift'||type==='shelter'?window.zyklusWorkday:window.zyklusStoryActivities).open(type,()=>mark(type==='shelter'?'episodeEnd':type))}
addEventListener('story-activity-close',()=>{activity=false;keys.clear();if(storyType==='shiftList'&&progress.shiftList)toast('Your shift starts at the third gate.');if(storyType==='workShift'&&progress.workShift)toast('Shift finished. There is a room behind the fourth gate.');storyType=null;canvas.focus()});
function swim(){activity=true;keys.clear();window.zyklusSwim.open()}
addEventListener('swim-close',()=>{activity=false;keys.clear();canvas.focus()});addEventListener('swim-finish',()=>mark('swim'));
function waitFor(text){showTalk([{speaker:'Notes',title:'One thing at a time',text}])}
function chapterSpots(){
 if(scene==='university')return[{x:150,label:'Back to the ring',run:()=>go('main',650)},{x:855,label:'Examine the readings',done:progress.university,run:()=>say('university',null,{label:'Check the readings →',run:()=>startActivity('measure')})},...(progress.university?[{x:1310,label:'Talk to Toren',done:progress.torenMorning,run:()=>say('torenMorning',()=>mark('torenMorning'))}]:[])];
 if(scene==='outerRing')return[{x:170,label:'Back to the pool',run:()=>go('main',1440)},{x:815,label:'Examine the red section',done:progress.outerRing,run:()=>say('outerRing',()=>mark('outerRing'))},{x:1470,label:'Go home',run:()=>progress.outerRing?go('main',785):waitFor('The stripe is red. Examine this section before going home.')}];
 if(scene==='sarnRoom')return[{x:180,label:'Back to the ring',run:()=>go('main',785)},{x:780,label:'What was said',done:progress.interrogation,run:()=>say('interrogation',null,{label:'Check the facts →',run:()=>storyActivity('interrogation')})},...(progress.interrogation?[{x:1450,label:'The knock at the back door',done:progress.torenNight,run:()=>say('torenNight',()=>mark('torenNight'),{label:'Follow Toren →',run:()=>go('delivery',230)})}]:[])];
 if(scene==='delivery')return[{x:140,label:'Back inside',run:()=>go('sarnRoom',1400)},{x:1330,label:'Take the delivery corridor',done:progress.delivery,run:()=>say('delivery',null,{label:'Reach the wagon →',run:()=>startActivity('delivery')})},...(progress.delivery?[{x:1560,label:'To the transfer hall on Level Nine',run:()=>go('levelNine',230)}]:[])];
 if(scene==='levelNine')return[{x:230,label:'Look round the transfer hall',done:progress.arrivalNine,run:()=>say('arrivalNine',()=>mark('arrivalNine'))},{x:920,label:progress.shiftList?'The third gate · Start work':'The shift list at the third gate',done:progress.shiftList,run:()=>progress.shiftList?storyActivity('workShift'):progress.arrivalNine?say('shiftList',null,{label:'Check the vacancies →',run:()=>storyActivity('shiftList')}):waitFor('Look round first. Find out where you are.')},...(progress.workShift?[{x:1430,label:'After work · The fourth gate',done:progress.episodeEnd,run:()=>storyActivity('shelter')}]:[])];
 return[{x:220,label:'Examine the wooden table',done:progress.home,run:()=>say('home',()=>mark('home'))},{x:630,label:'To the university',run:()=>progress.home?go('university',230):waitFor('Look round your home before leaving.')},{x:785,label:progress.door?'Back inside':'Try the panel',done:progress.door,run:()=>{if(progress.door){go('sarnRoom',230);return}if(!progress.outerRing){waitFor('Check the readings at the university. Meet Bela at the pool. Then take the outer ring home.');return}red=12;say('door',()=>{mark('door');go('sarnRoom',230)})}},{x:1390,label:'Talk to Bela',done:progress.bela,run:()=>{if(!progress.torenMorning){waitFor('Visit the university and finish checking the readings first.');return}say('bela',()=>mark('bela'),{label:'Swim a race →',run:swim})}},{x:1610,label:'To the outer ring',run:()=>progress.bela&&progress.torenMorning?go('outerRing',230):waitFor('Bela is waiting at the pool. Meet her before taking the outer ring home.')}]
}
function spots(){return [...chapterSpots(),...(window.zyklusDiscoveries?.spots(scene,progress)||[]).map(p=>({...p,optional:true,done:progress['detail_'+p.id],run:()=>showTalk([{speaker:'Notes',title:p.title,text:p.text}],()=>mark('detail_'+p.id))}))]}
function councilChapter(){if(!progress.episodeEnd)return;mapOpen=false;journalOpen=false;$('#mapView').hidden=true;$('#notebook').hidden=true;activity=true;keys.clear();window.zyklusCouncil.open(()=>mark('councilEnd'))}
addEventListener('council-close',()=>{activity=false;keys.clear();canvas.focus()});
function bracksChapter(){if(!progress.episodeEnd)return;mapOpen=false;journalOpen=false;$('#mapView').hidden=true;$('#notebook').hidden=true;activity=true;keys.clear();window.zyklusBracks.open(()=>mark('bracksEnd'))}
addEventListener('bracks-close',()=>{activity=false;keys.clear();canvas.focus()});
function recap(){const entries=window.zyklusDiscoveries.recap(progress).map(e=>({speaker:'Notes',...e}));if(progress.bracksEnd)entries.push({speaker:'Notes',title:'Bracks’ notes',text:'The register, the daily slip and the tag. What the file can hold. What it cannot.'});if(progress.councilEnd)entries.push({speaker:'Notes',title:'Rena’s memory',text:'Kelb’s report. Sivar’s choice. The name Rena was told not to write.'});showTalk(entries,null,!progress.councilEnd?{label:'Visit the Council →',run:councilChapter}:progress.bracksEnd?null:{label:'Follow Bracks →',run:bracksChapter})}
function nearest(){return spots().filter(p=>Math.abs(x-p.x)<85).sort((a,b)=>Math.abs(a.x-x)-Math.abs(b.x-x))[0]}
function interact(){if(!canMove()||body.roll||jump>0||takeoff>0||landing>0)return;nearest()?.run()}
$('#touchE').onclick=interact;function leap(){if(canMove()&&jump===0&&!landing&&!takeoff&&!body.roll&&body.crouch<.1&&!window.zyklusTraversal.requiresDuck(scene,x)){takeoff=.09;tone(170,.08)}}$('#touchJump').onclick=leap;function roll(){if(canMove()&&jump===0&&vy===0&&!landing&&!takeoff)motion.roll(body)}$('#touchRoll').onclick=roll;
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(dialog.open){if(k==='enter'&&!e.repeat&&document.activeElement.tagName!=='BUTTON'){e.preventDefault();$('#close').click()}return}if(document.activeElement?.tagName==='BUTTON'&&(k===' '||k==='enter'))return;if(['arrowleft','arrowright','arrowdown',' '].includes(k))e.preventDefault();if(!active||activity)return;if(document.activeElement?.tagName==='BUTTON'&&(k===' '||k==='enter'))return;if(k==='j'&&!e.repeat){notebook();return}if(k==='m'&&!e.repeat){mapToggle();return}if(k==='escape'){if(mapOpen)mapToggle();if(journalOpen)notebook();return}if(!canMove())return;keys.add(k);if(!e.repeat){if(k==='e')interact();if(k===' ')leap();if(k==='r')roll()}});
addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(!e.shiftKey)keys.delete('shift')});addEventListener('blur',()=>{keys.clear();motion.stop(body)});dialog.addEventListener('close',()=>keys.clear());document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(canMove())keys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key)});
function poolDepth(px){const t=Math.min(1,Math.max(0,(px-910)/80));return t*t*(3-2*t)}
function ground(px){return scene==='main'?540-26*poolDepth(px)-Math.max(0,Math.min(76,(px-1520)*.76)):scene==='university'?545:scene==='sarnRoom'?548:scene==='outerRing'?552:565}
function actorSprite(px,py,moving){
 const h=scene!=='main'?143:110-9*poolDepth(px);
 ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(px,ground(px),body.roll?21:12,2,0,0,7);ctx.fill();
 if(body.roll){const phase=1-body.roll/.62;motion.draw(ctx,images.actorActions,4+Math.min(3,Math.floor(phase*4)),px,py,h,body.rollDir)}
 else if(jump>0||takeoff>0||landing>0){const compression=takeoff>0?1-takeoff/.09:landing>0?landing/.14:.35+.65*Math.min(1,jump/39);window.zyklusGait.draw(ctx,images.actor,px,py,h,dir,0,0,compression)}
 else if(body.crouch>.05){const f=body.crouch<.6?0:moving?2+Math.floor(body.distance/17)%2:1;motion.draw(ctx,images.actorActions,f,px,py,h,dir)}
 else if(moving)window.zyklusGait.draw(ctx,images.actor,px,py,h,dir,body.gaitDistance,body.run,null,scene==='main'?ground:null,gaitPhase);
 else motion.idle(ctx,images.actor,px,py,h+Math.sin(time*1.6)*.28,dir);
 $('#runControl').hidden=!canMove();$('#runControl').setAttribute('aria-pressed',String(keys.has('shift')));
 canvas.dataset.movement=body.roll?'roll':jump>0?'jump':landing>0?'land':body.crouch>.05?'crouch':moving?(body.run>.5?'run':'walk'):'idle';
}
function advanceGait(oldX,oldGait){const midX=(oldX+x)/2,gaitHeight=scene==='main'?110-9*poolDepth(midX):143,terrainMix=window.zyklusGait.terrainAmount(scene==='main'?ground:null,midX);gaitPhase+=(body.gaitDistance-oldGait)/(380*(gaitHeight/650)*(1-49/95*terrainMix));}
function frame(now){const dt=Math.min(.05,(now-last)/1000||.016);last=now;time+=dt;if(travel){travel.elapsed+=dt;if(travel.phase==='approach'){const gap=travel.target-x;if(Math.abs(gap)<4||travel.elapsed>.85){motion.stop(body);travel.phase='fade';travel.elapsed=0}else{const oldX=x,oldGait=body.gaitDistance;motion.step(body,dt,Math.sign(gap));x=body.x;dir=body.dir;advanceGait(oldX,oldGait)}}else{transition=Math.min(1,travel.elapsed/.18);if(travel.elapsed>=.18){const next=travel;travel=null;arrive(next.dest,next.pos)}}}landing=Math.max(0,landing-dt);red=Math.max(0,red-dt);if(!travel)transition=Math.max(0,transition-dt*3.5);let moving=travel?.phase==='approach'&&Math.abs(body.v)>3;
 if(canMove()){
  if(takeoff>0){takeoff=Math.max(0,takeoff-dt);if(takeoff===0)vy=210}
  const dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),duck=jump===0&&(keys.has('s')||keys.has('arrowdown')||window.zyklusTraversal.requiresDuck(scene,x));if(window.zyklusTraversal.requiresDuck(scene,x))body.crouch=Math.max(.7,body.crouch);
  const before=body.distance,oldX=body.x,oldGait=body.gaitDistance;motion.step(body,dt,dx,duck,keys.has('shift'));const passage=window.zyklusTraversal.resolve(scene,oldX,body.x,jump,body.crouch,body.roll);traversalHint=passage.hint;if(passage.blocked){body.x=passage.x;body.v=0;body.roll=0;body.distance=before+Math.abs(body.x-oldX);body.gaitDistance=oldGait+Math.abs(body.x-oldX)/(1+.3*body.run)}x=body.x;dir=body.dir;moving=Math.abs(body.v)>3;
  advanceGait(oldX,oldGait);
  if(moving&&!body.roll&&jump===0){walk+=body.distance-before;if(walk>48){tone(75+Math.random()*20,.05,'triangle',duck?.007:.015);walk=0}}
  if(jump>0||vy>0){jump=Math.max(0,jump+vy*dt);vy-=570*dt;if(jump===0){vy=0;landing=.14;tone(65,.06,'triangle',.012)}}
 }else{if(travel?.phase!=='approach')motion.stop(body);takeoff=0;}if(window.zyklusTraversal.requiresDuck(scene,x))body.crouch=Math.max(.7,body.crouch);
 const gap=x-follower.x,target=Math.abs(gap)>65?Math.sign(gap)*Math.min(265,(Math.abs(gap)-55)*4):0;
 follower.v+=(target-follower.v)*(1-Math.exp(-dt*8));const delta=canMove()?follower.v*dt:0;follower.x=Math.max(90,Math.min(1580,follower.x+delta));follower.run+=(Math.max(0,Math.min(1,(Math.abs(follower.v)-120)/120))-follower.run)*(1-Math.exp(-dt*5));follower.distance+=Math.abs(delta)/(1+.3*follower.run);if(Math.abs(delta)>.04)follower.dir=Math.sign(delta);companionSpeed=Math.abs(delta)/dt;
 zoom+=(targetZoom-zoom)*Math.min(1,dt*6);const scale=Math.max(W/1672,H/941)*zoom,halfW=W/scale/2,halfH=H/scale/2;let tx=active?x:650,ty=scene==='main'?470:490;tx=Math.max(Math.min(halfW,836),Math.min(1672-halfW,tx));ty=Math.max(Math.min(halfH,470),Math.min(941-halfH,ty));cameraX+=(tx-cameraX)*Math.min(1,dt*4);cameraY+=(ty-cameraY)*Math.min(1,dt*4);ctx.fillStyle='#081017';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2,H/2);ctx.scale(scale,scale);ctx.translate(-cameraX,-cameraY);ctx.imageSmoothingEnabled=false;const bg=images[scene];if(bg?.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0,1672,941);
if(scene==='main'){for(let i=0;i<14;i++){ctx.fillStyle='#b8e1db14';ctx.fillRect(1030+Math.sin(time*1.5+i)*12,550+i*7,560,1)}if(red>0||progress.door){ctx.fillStyle=`rgba(239,53,34,${.13+.07*Math.sin(time*3)})`;ctx.fillRect(745,382,6,147);ctx.fillRect(755,530,230,3)}}for(let i=0;i<35;i++){ctx.fillStyle='#ded2ae25';ctx.fillRect((i*193+time*(1+i%3)*3)%1672,270+(i*47)%255+Math.sin(time+i)*3,1,1)}
if(active)window.zyklusLife.draw(ctx,images,{scene,time,x,progress});
for(const p of spots()){const yy=ground(p.x)-105+Math.sin(time*2+p.x)*3;ctx.fillStyle=p.done?'#85b0a488':p.optional?'#91b9b9bb':'#e7c68bd0';ctx.beginPath();ctx.moveTo(p.x,yy-4);ctx.lineTo(p.x+4,yy);ctx.lineTo(p.x,yy+4);ctx.lineTo(p.x-4,yy);ctx.fill()}
if(scene==='outerRing'){
 const bay=Math.min(4,Math.floor(x/335));
 for(let i=0;i<5;i++){const lit=i<=bay+1||progress.outerRing;ctx.fillStyle=lit?'#ed4e39':'#d5d9c8';ctx.shadowColor=lit?'#ff3521':'transparent';ctx.shadowBlur=lit?12:0;ctx.fillRect(i*335+15,534,305,3);ctx.shadowBlur=0;if(lit){ctx.fillStyle='#eb321c0d';ctx.fillRect(i*335+15,280,305,254)}}
}
if(active){
 const companion=scene==='levelNine'||scene==='delivery'&&progress.torenNight;
 const waiting=scene==='sarnRoom'&&progress.interrogation&&!progress.torenNight;
 if(companion||waiting){const px=companion?follower.x:1450;if(companion&&companionSpeed>4)window.zyklusGait.draw(ctx,images.toren,px,ground(px)-(scene==='delivery'?28:0),scene==='delivery'?125:139,follower.dir,follower.distance,follower.run);else motion.idle(ctx,images.toren,px,ground(px)-(scene==='delivery'?28:0),scene==='delivery'?125:139,companion?follower.dir:-1)}
 window.zyklusTraversal.draw(ctx,images,scene);
 actorSprite(x,ground(x)-jump,moving);
}ctx.restore();const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#040a1040');g.addColorStop(.35,'#00000000');g.addColorStop(.8,'#00000000');g.addColorStop(1,'#030a1066');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(transition>0){ctx.fillStyle=`rgba(5,12,17,${transition})`;ctx.fillRect(0,0,W,H)}const roomNames={university:'The university',delivery:'The delivery corridor',outerRing:'The outer ring',sarnRoom:'House Sarn · Evening',levelNine:'The transfer hall'};$('#room').textContent=roomNames[scene]||(x<610?'House Sarn':x<985?'The ring':'The pool');$('#level').textContent=scene==='levelNine'?'09':'10';$('#district').textContent=scene==='levelNine'?'THE TRANSFER HALL':'LEVEL TEN · THE BOTTOM';$('#climate').textContent=scene==='levelNine'?'Early shift · A filed purpose':'19 °C · Level Ten';$('#zoomLabel').textContent=zoom<1.1?'OVERVIEW':'DETAIL';const p=canMove()&&jump===0&&!takeoff&&!landing&&!body.roll?nearest():null;$('#hint').hidden=!p&&!(canMove()&&traversalHint);if(p)$('#hint').textContent=`E · ${p.label}`;else if(canMove()&&traversalHint)$('#hint').textContent=traversalHint;window.zyklusLife.audio(audio,sound,{scene,x,active,paused:activity||dialog.open||mapOpen||journalOpen});requestAnimationFrame(frame)}requestAnimationFrame(frame);

document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();motion.stop(body)}if(document.hidden&&audio)audio.suspend();else if(sound&&audio)audio.resume()});
