(() => {
 const host=document.createElement('section');host.id='workday';host.hidden=true;host.setAttribute('role','dialog');host.setAttribute('aria-modal','true');host.setAttribute('aria-labelledby','workTitle');document.querySelector('main').append(host);
 const $=s=>host.querySelector(s),colors=[['Blue','◆','#4e9bb9'],['Circle','●','#d3aa59'],['Green','▲','#7ca68a']],cargo=[0,2,1,0,1,2];
 let kind,callback,previous,index=0,tilted=false,pushed=false,rested=false,finished=false,seen=new Set();
 function close(){if(host.hidden)return;host.hidden=true;window.dispatchEvent(new Event('story-activity-close'));previous?.focus?.()}
 function finish(){if(finished)return;finished=true;callback?.(kind)}
 function shell(title,sub,body){host.innerHTML=`<div class="work-inner"><header class="work-head"><div><small>ZYKLUS · LEVEL NINE</small><h2 id="workTitle">${title}</h2><p>${sub}</p></div><button id="workExit">Back to the hall ×</button></header>${body}<p id="workFeedback" role="status"></p></div>`;$('#workExit').onclick=close}
 function feedback(s){$('#workFeedback').textContent=s}
 function renderWork(){
  const c=colors[cargo[index]];
  shell('One shift. One place.','Hedd shows you: tilt, then push. Six containers stand for Lian’s seven-hour shift.',`<div class="dock-scene"><div class="dock-time">EARLY SHIFT <b>${index} / 6 CONTAINERS</b></div><div class="dock-worker"></div><div class="dock-crate" style="--cargo:${c[2]}"><span>${c[1]}</span><strong>${c[0].toUpperCase()}</strong></div></div><div class="dock-panel"><div><small>01 · THE METHOD</small><h3>Tilt. Then push.</h3><p>Keep the container on its edge. Then push it onto the matching wagon.</p><div class="dock-tools"><button id="tilt">1 · Tilt the container</button><button id="push" disabled>2 · Push onto the wagon</button></div></div><div><small>02 · THE MARKING</small><h3>Match colour and symbol.</h3><div class="dock-destinations">${colors.map((a,i)=>`<button data-cart="${i}" disabled style="--cargo:${a[2]}"><b>${a[1]}</b>${a[0]}</button>`).join('')}</div></div></div>`);
  $('#tilt').onclick=()=>{tilted=true;$('.dock-crate').classList.add('tilted');$('#tilt').disabled=true;$('#push').disabled=false;$('#push').focus();feedback('The edge takes the weight.');tone(110,.1,'triangle')};
  $('#push').onclick=()=>{if(!tilted)return;pushed=true;$('.dock-worker').classList.add('pushing');$('.dock-crate').classList.add('pushed');$('#push').disabled=true;host.querySelectorAll('[data-cart]').forEach(b=>b.disabled=false);host.querySelector('[data-cart]').focus();feedback('The container is on the wagon. Match its marking.')};
  host.querySelectorAll('[data-cart]').forEach(b=>b.onclick=()=>{if(!pushed)return;if(+b.dataset.cart!==cargo[index]){feedback('The markings do not match. Check the colour AND the symbol.');return}index++;tilted=false;pushed=false;tone(330,.12);if(index===4&&!rested){renderRest();return}if(index===cargo.length){renderPay();return}renderWork();$('#tilt').focus();feedback(index===1?'Blue means Level Ten, he says. Better packed, so the container weighs more and there’s less inside.':'The two places have been open since March. Nine people do the work of eleven and get paid for nine.')});
 }
 function renderRest(){shell('In the sixth hour.','Toren puts down a container and stays leaning on it with one hand.',`<div class="dock-scene rest"><div class="dock-worker"></div><div class="dock-toren"></div><div class="dock-time">A MOMENT TO REST</div></div><div class="work-card"><h3>“I just stood up too fast.”</h3><p>He has not eaten since Monday. Lian stands between him and the hall.</p><button id="restToren">Stay with Toren</button></div>`);$('#restToren').onclick=()=>{rested=true;renderWork();feedback('Three minutes pass. Nobody comes. You finish the shift together.');$('#tilt').focus()}}
 function renderPay(){finish();shell('13:00 · The shift ends.','A shift is a purpose, not access. Working doesn’t feed you.',`<div class="dock-scene"><div class="dock-time">6 / 6 · SHIFT COMPLETE</div><div class="dock-worker"></div><div class="dock-toren"></div></div><div class="work-card"><h3>You worked. Your name is still on no list for food.</h3><p>Behind the third gate: two rations and water on a bench. Somebody used their own Allocation.</p><button id="afterWork">To the rations and the fourth gate →</button></div>`);$('#afterWork').onclick=close}
 const details={mats:['Two mats','One is worn. The second is new. The room is used for lids. Someone has prepared two places to sleep.'],water:['Half a container of water','Two rations. Water. A woman offers the room until morning. She gives no name. Asks for nothing. Who knew we were coming?'],bolt:['The bolt is outside','No lock on this side. The bolt is outside. You hear the night shift in the hall.'],arm:['Toren’s arm','The sleeve sticks to the wound. Lian has little water. Nothing clean for a bandage. She does what she can.']};
 function renderShelter(){shell('Behind the fourth gate.','Look around the room. Help Toren before Lian lies down.',`<div class="shelter-scene"><button data-detail="mats" class="hotspot mats">① The mats</button><button data-detail="water" class="hotspot water">② Rations and water</button><button data-detail="bolt" class="hotspot bolt">③ The outside bolt</button><button data-detail="arm" class="hotspot arm">④ Toren’s arm</button></div><div class="shelter-detail work-card"><small id="shelterCount">${seen.size} / 4 OBSERVATIONS</small><h3 id="detailTitle">A room for one night.</h3><p id="detailText">Eight stacks of lids, two mats and a door. Select the marked objects.</p><button id="sleep" disabled>Lie down for the night →</button></div>`);
 host.querySelectorAll('[data-detail]').forEach(b=>{if(seen.has(b.dataset.detail))b.classList.add('observed');b.onclick=()=>{const key=b.dataset.detail;seen.add(key);b.classList.add('observed');$('#detailTitle').textContent=details[key][0];$('#detailText').textContent=details[key][1];$('#shelterCount').textContent=`${seen.size} / 4 OBSERVATIONS`;$('#sleep').disabled=seen.size!==4;tone(260,.08)}});
 $('#sleep').onclick=()=>{if(seen.size!==4)return;finish();shell('One level behind you.','LIAN’S JOURNEY · EPISODE 01',`<div class="shelter-scene epilogue"><div class="end-words"><small>NOTHING WAS LOST.</small><h3>Somebody knew<br>we were coming.</h3><p>Toren sleeps. Lian hears the night shift outside.<br>Someone touches the bolt. It does not slide.</p></div></div><div class="work-card"><p>Your observations stay in the notebook. You can keep exploring the places you have found.</p><button id="finishDay">Back to the city →</button></div>`);$('#finishDay').onclick=close;$('#finishDay').focus()};
 }
 window.zyklusWorkday={open(next,onDone){previous=document.activeElement;kind=next;callback=onDone;index=0;tilted=false;pushed=false;rested=false;finished=false;seen=new Set();host.hidden=false;kind==='workShift'?renderWork():renderShelter();$('#workExit').focus()},close};
 document.addEventListener('keydown',e=>{if(host.hidden)return;e.stopImmediatePropagation();if(e.key==='Escape'){e.preventDefault();close();return}if(!e.repeat&&(e.key==='1'||e.key==='2')){const b=$(e.key==='1'?'#tilt':'#push');if(b&&!b.disabled){e.preventDefault();b.click()}}if(e.key==='Tab'){const controls=[...host.querySelectorAll('button:not(:disabled)')],first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}},true);
 document.addEventListener('keyup',e=>{if(!host.hidden)e.stopImmediatePropagation()},true);
})();